server:
  port: 8062

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5442/media_db
    username: media
    password: media
  flyway:
    enabled: true
    locations: classpath:db/migration

minio:
  url: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  bucket: fitness-tracker
