server:
  port: 8061

spring:
  application:
    name: workout-service
  datasource:
    url: jdbc:postgresql://localhost:5441/workout_db
    username: workout
    password: workout
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        type:
          preferred_duration_jdbc_type: INTERVAL_SECOND
    show-sql: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.postgresql.jdbc: TRACE
#    org.postgresql.sql: DEBUG